### ISSUE TITLE
Dockerで立ち上げたMySQLにSequel Proから接続できない

### ISSUE THREAD

**Issue by rema424** [rema424/go-post-sample-app#60]
`MySQL の応答: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/lib/plugin/caching_sha2_password.so, 2): image not found`

**Comment by rema424** [comment]
参考: [Sequre ProでMySQLにログインできない](https://qiita.com/r641ywork/items/7f0ca12ced72363f9448)

**Comment by rema424** [comment]
### 再現手順

`docker-compose.yml`

```yml
version: "3"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: RootPassw0rd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: Passw0rd
      TZ: Asia/Tokyo
    tty: true
```

```bash
docker-compose up db
```

`Sequel Pro`

- 標準
  - 名前: （任意の名称）
  - ホスト: 127.0.0.1
  - ユーザ名: testuser
  - パスワード: Passw0rd
  - データベース: testdb
  - ポート: 3306

接続をクリックすると次のエラー。

```
MySQL の応答: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/lib/plugin/caching_sha2_password.so, 2): image not found
```

### 調査結果

- MySQL8.0以上からセキュリティ向上のため認証方法が変更された
- Sequel Proは新しい認証方法に未対応

上記二つが重なったことで接続が出来なかった模様。
Dockerだからではない。

対応策としては、Sequel Proで接続する前にターミナルからデータベースにアクセスして認証方法をMySQL8.0以前のものに変更すれば良い。

### 対応方法

```bash
docker-compose up -d db
docker-compose exec db bash

mysql -u testuser -D testdb -p -h 127.0.0.1
Enter password: Passw0rd

SELECT host, user, plugin FROM mysql.user;
\q

mysql -u root -p -h 127.0.0.1
Enter password: RootPassw0rd

SELECT host, user, plugin FROM mysql.user;
ALTER USER 'testuser'@"%" IDENTIFIED WITH mysql_native_password BY 'Passw0rd';
SELECT host, user, plugin FROM mysql.user;
\q
```

この作業が完了したのちSequel Proで接続を試すと成功します。
